# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Insights-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Insights-Demo
#  pod 'InstantSearchInsights', '~> 1.0'
  pod 'InstantSearchInsights', :path => '../'
  pod 'InstantSearchClient', '~> 5.0'
  pod 'Nuke'
  pod 'CFNotify'
end
